- pipeline-modules/deployment-service/gcp/cloud-run.yaml
* Use user creds to deploy cloud run app
* Use pipleine_env_file to add enviroment to downstream app
* Use yaml to deploy instead of gcloud arguments
> VAN-1959 Use user creds to deploy cloud run app

- pipeline-modules/deployment-service/gcp/cloud-run.yaml
- pipeline-modules/deployment-service/gcp/pipeline-config.yaml
For the app-deployment pipelines, we switch the gcloud CLI to use the user provided service account so that, the pipeline modules gets the access from the given service account rather then relying on the constant cloud build service account.
> VAN-1868 switch gcloud creds

- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
- pipeline-modules/deployment-service/gcp/basic-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/cloud-run.yaml
- pipeline-modules/deployment-service/gcp/istio-gke-regional.yaml
change pipeline modules input rule `minlength=1` to `required`
because the input field will not show with required flag otherwise.
althought the validation rule would still work on submit
> VAN-2103 fix required input field rules

- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
- pipeline-modules/deployment-service/aws/pipeline-config.yaml
- pipeline-modules/deployment-service/gcp/basic-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/istio-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/pipeline-config.yaml
On aws pipelines, jq seems already installed but it was jq 1.5
while we were upgrading it to 1.6 (for consistency)
but the PATH variable was set in a way that the newly installed one
was getting overridden.
So we fix it by overriding the previous one.
Also, the format `jq -aRs` is not backward compatible so changing it to
`jq -aRs .` since that makes it more resilient and consistent
to the other occurrences
> VAN-2096 fix jq setup and make usage consistent

- pipeline-modules/deployment-service/aws/pipeline-config.yaml
Adjustment to previous commit to fix the syntax issue on AWS
related to the expected_variable_names handling. Needed to switch
pipeline from sh to bash as well as setup proper multi-line syntax.
> VAN-2156 Fix AWS environment variable handling

- pipeline-modules/infra-service/aws/pipeline-config.yaml
some terraform apply runs beyond 1hr
> VAN-2277 Increase aws build timeout for terraform

- pipeline-modules/deployment-service/aws/test_module.yaml
- pipeline-modules/deployment-service/gcp/test_module.yaml
In order to use the test_module, we need it to have an
inputArtifactType. Using a git repo for now.
> VAN-2203 Add inputArtifactType to meta

- pipeline-modules/app-service/aws/bash.yaml
- pipeline-modules/app-service/aws/docker-build-n-push.yaml
- pipeline-modules/app-service/aws/go-build.yaml
- pipeline-modules/app-service/gcp/docker-build-n-push.yaml
- pipeline-modules/app-service/gcp/go-build.yaml
- removed "required" and added "internal" for docker-build-n-push
- Added selection of "go_version" to the go-build module
- Added bash module for AWS
> VAN-2308 Updates to support app-integration testing

- pipeline-modules/infra-service/aws/pipeline-config.yaml
- pipeline-modules/infra-service/aws/terraform.yaml
- pipeline-modules/infra-service/azure/terraform.yaml
- pipeline-modules/infra-service/gcp/pipeline-config.yaml
- pipeline-modules/infra-service/gcp/terraform.yaml
The state file must be in the code directory before init.
In order to maintain all artifacts together
use 'terraform state push' command to copy the state to
the backend (working dir) before init.
This command may also work better (compared to straight 'cp')
with different backends.
Also add missing pipeline queue timeout parameters.
> VAN-2255 Load global state to working dir before init

- pipeline-modules/infra-service/azure/terraform.yaml
This fixes the issue of terraform not being installed correctly in the
infra pipeline.
Also, this fixes VAN-2345 - need to upload the TF init log after each
step.
Added a set -x so that we can see the script code being executed in
the pipeline.
> VAN-2344 Fix TF version install on Azure

- pipeline-modules/app-service/azure/bash.yaml
- pipeline-modules/app-service/azure/git-access.yaml
- pipeline-modules/app-service/azure/git-clone.yaml
- pipeline-modules/app-service/azure/pipeline-config.yaml
- pipeline-modules/app-service/azure/test_module.yaml
- pipeline-modules/deployment-service/aws/test_module.yaml
- pipeline-modules/deployment-service/azure/test_module.yaml
- Add required modules for azure app integration:
git-access, git-clone, pipeline-config
- Add the test_module used by the Opstest scenario
- Change the artifact type for test_module to container
Additional unrelated fix:
- Add pipeline summary function to deployment test_module
> VAN-2366 Add support for Azure appint to Opstest

- pipeline-modules/infra-service/aws/terraform.yaml
- pipeline-modules/infra-service/azure/terraform.yaml
- pipeline-modules/infra-service/gcp/terraform.yaml
Add Terraform destroy operation to Azure module.
Also fix plan generation in all modules.
In order to generate destroy plan one must provide '-destroy'
option to plan command.
"This will run terraform plan in destroy mode,
showing you the proposed destroy changes without executing them."
Previous code was attempting to do that but because of the 'tf_action'
value only apply plan would be generated (this would not affect destroy
itself as that does not use plan file).
This patch adds new 'plan-destroy' action that generates destroy plan.
> VAN-2310 Add TF destroy for Azure and fix plan

- pipeline-modules/infra-service/aws/terraform.yaml
looks for `codepipes_init.sh` in working dir
if the file existis, we add `chmod +x` on it
and then execute it.
> VAN-2406 run init script in infra-tf (hot-fix for zendesk)

- pipeline-modules/deployment-service/azure/basic-aks-module.yaml
- pipeline-modules/infra-service/azure/terraform.yaml
Added -input=false parameter on pipelines so that if a required the input is not provided terraform does not keep waiting for input and fails immediately.
> VAN-2454 added input=false flag for terraform

- pipeline-modules/app-service/aws/git-clone.yaml
- pipeline-modules/app-service/aws/java-unit-test.yaml
- pipeline-modules/app-service/aws/sonar-mvn.yaml
Added sonarCloud and sonarQube implementation
Added unit test template for java using maven
Updated path change to git clone, to access working directory for subsequent templates
PS: I have kept the version pinned for sonar and maven because their mvn:sonar was working with another version of sonar and maven. need to improve sonar template to work without maven plugin [VAN-2502](https://cldcvr.atlassian.net/browse/VAN-2502)
> VAN-2485 Add Integration Modules (sonar and java-unit-test)

- pipeline-modules/app-service/aws/bash.yaml
- pipeline-modules/app-service/aws/docker-build-n-push.yaml
- pipeline-modules/app-service/aws/git-access.yaml
- pipeline-modules/app-service/aws/git-clone.yaml
- pipeline-modules/app-service/aws/go-build.yaml
- pipeline-modules/app-service/aws/go-scan.yaml
- pipeline-modules/app-service/aws/pipeline-summary.yaml
Aws code build does not create new containers for each step as a result multiple statements in the build pipeline conflict with the commands.
Moved all the commands from multiple templates to build steps to avoid any conflict. 
TODO: Need to write a template creation guideline document  (https://cldcvr.atlassian.net/browse/VAN-1726)
> VAN-2549 Remove change directory commands and group everything into build step

- pipeline-modules/deployment-service/gcp/cloud-run.yaml
The default value is being specified as an integer but the input
is declared as a string. For consistency with other places we have
ports defined, switching to integer.
> VAN-2635 Change type of containerPort to integer

- pipeline-modules/infra-service/aws/terraform.yaml
- pipeline-modules/infra-service/azure/terraform.yaml
- pipeline-modules/infra-service/gcp/terraform.yaml
Terraform state must be present in the working directory
before running init. It must be called terraform.tfstate.
We used terraform push command to achieve this. This
command is primarily for working with remote backends.
It performs additional checks.
Unfortunatelly it fails on TF >= 1.2.0
It requires init to be done first.
This is not compatible with our use to initialize the working
directory before init.
Since we do not really require the push as we managed the state
ourselves we can instead just copy the state file to the working directoy
to achieve the same result.
> VAN-2748 Copy TF state instead of using push

- pipeline-modules/infra-service/aws/component.yaml
- pipeline-modules/infra-service/azure/component.yaml
- pipeline-modules/infra-service/gcp/component.yaml
Declare all component outputs as sensitive in Terraform.
This is to make the exported outputs compatible with
sensitive module outputs.
This does not affect how they are stored in the state.
Older Terraform versions ignore the senitive attribute.
> VAN-2920 Mark component exports as sensitive

- helm/gcp/basic-gke/templates/ingress.yaml
- helm/gcp/istio-gke/templates/gke-ingress.yaml
Upgrade the beta version to stable version of k8s cluster API
> VAN-2953 | Upgrade GKE Cluster API version

- helm/gcp/basic-gke/templates/ingress.yaml
- helm/gcp/istio-gke/templates/gke-ingress.yaml
API decrpated for k8s version >=1.22+
`Ingress` and `IngressClass` resources have graduated to `networking.k8s.io/v1`. Ingress and IngressClass types in the `extensions/v1beta1` and `networking.k8s.io/v1beta1` API versions are deprecated and will no longer be served in 1.22+. Persisted objects can be accessed via the `networking.k8s.io/v1` API. Notable changes in v1 Ingress objects (v1beta1 field names are unchanged):
* `spec.backend` -> `spec.defaultBackend`
* `serviceName` -> `service.name`
* `servicePort` -> `service.port.name` (for string values)
* `servicePort` -> `service.port.number` (for numeric values)
* `pathType` no longer has a default value in v1; "Exact", "Prefix", or "ImplementationSpecific" must be specified
Other Ingress API updates:
* backends can now be resource or …
> VAN-2984 | Adding condition for handle deprecated k8s API

- pipeline-modules/app-service/aws/test_module.yaml
- pipeline-modules/app-service/azure/test_module.yaml
- pipeline-modules/app-service/gcp/pipeline-config.yaml
- pipeline-modules/app-service/gcp/test_module.yaml
- pipeline-modules/deployment-service/aws/test_module.yaml
- pipeline-modules/deployment-service/azure/test_module.yaml
- pipeline-modules/deployment-service/gcp/pipeline-config.yaml
- pipeline-modules/deployment-service/gcp/test_module.yaml
- pipeline-modules/infra-service/aws/test_module.yaml
- pipeline-modules/infra-service/gcp/pipeline-config.yaml
- pipeline-modules/infra-service/gcp/test_module.yaml
Some modules declares inputs as number type where as it really needs integer type.
This change fixes the issue.
> VAN-3207 fix integer vs number usage

- build-pipeline/vg-pipeline-module-pr.yml
the tests previously expected the vg-api build to contain pipeline modules. but after the upcoming VAN-3219 change, we'll no longer include it in the builds and hence this change has to run `make db-update`
> VAN-3321 run db-update before tests

- pipeline-modules/common/azure/env-files.yaml
- pipeline-modules/common/azure/pipeline-config.yaml
- pipeline-modules/deployment-service/azure/azure-functions.yaml
- pipeline-modules/deployment-service/azure/azure-web-app.yaml
A recent change introduced an inconsistency in how the workspace
directory we being set across the Azure pipeline modules. This
fixes that and consistently sets it to Build.SourcesDirectory.
> VAN-3634 Fix workspace directory for azure

- cloud-builders/make/Dockerfile
- pipeline-modules/app-service/aws/bash.yaml
- pipeline-modules/app-service/aws/make-target.yaml
- pipeline-modules/app-service/azure/bash.yaml
- pipeline-modules/app-service/azure/make-target.yaml
- pipeline-modules/app-service/gcp/bash.yaml
- pipeline-modules/app-service/gcp/make-target.yaml
- pipeline-modules/common/azure/env-files.yaml
Added "make-target" pipeline module for AWS, Azure and GCP. This
module allows the integration pipeline to call 1 or more targets
in a make file in sequence.
In order to have the secret env vars available to any downstream
processes (like references in the Makefile), needed to add an
"env" stanza to any steps/tasks that needed them. Also did this
for the env-files module as it won't actually work without this.
For GCP, this pipeline module also includes a new cloud-builder
container.
Also, recategorized "bash" to "utility" as I think it shows up
better in the UI this way.
> VAN-3243 Add pipeline module to call make targets

- pipeline-modules/app-service/aws/docker-build.yaml
- pipeline-modules/app-service/aws/docker-push.yaml
- pipeline-modules/app-service/aws/java-unit-test.yaml
- pipeline-modules/app-service/azure/docker-build.yaml
- pipeline-modules/app-service/azure/docker-push.yaml
- pipeline-modules/app-service/azure/java-unit-test.yaml
- pipeline-modules/app-service/gcp/docker-build.yaml
- pipeline-modules/app-service/gcp/docker-push.yaml
- Mark existing 'unit test' type modules as 'default'
- Mark existing 'Docker Build' modules as 'default' add more relevant keywords for discovery
- Add 'Docker Push' module split from docker-build-n-push
> VAN-3345 add default modules

- assets/scripts/git-clone.sh
- pipeline-modules/app-service/azure/make-target.yaml
- pipeline-modules/common/aws/env-files.yaml
- pipeline-modules/common/aws/git-clone.yaml
- pipeline-modules/common/azure/git-clone.yaml
- pipeline-modules/common/gcp/git-clone.yaml
- pipeline-modules/deployment-service/aws/artifact-config.yaml
- pipeline-modules/deployment-service/aws/run-bash-script.yaml
- pipeline-modules/deployment-service/azure/artifact-config.yaml
- pipeline-modules/deployment-service/azure/run-bash-script.yaml
- pipeline-modules/deployment-service/gcp/run-bash-script.yaml
Added a new deployment template - run-bash-script - for
AWS, GCP and Azure. It expects a GitCode artifact and the
name of a Bash script file that is present in the Git repo.
A list of parameters to the script can be provided and are
passed to the script when it is run.
All of the env vars (secret and not) are made available
to the script as well.
The pipeline exports an env var - CODEPIPES_DEPLOY_ACTION -
which can be used by the called script to distinguish between
"deploy" and "undeploy".
While working on this I noticed a few things about the
common scripts that could be improved:
- common git-clone.yaml was missing for Azure and GCP
- Azure was exposing a Git SHA - have made that available for all
> VAN-3376 Add deployment template for bash script

- pipeline-modules/app-service/gcp/node-build.yaml
We switched to pnpm for Stance and Codepipes but didn't update it in our CI-CD modules. I had to redo how the script works because Google cloud doesn't share state between steps. Now the whole thing runs as a single script.
> VAN-3614 Add pnpm to CI checks and fix npm checks

- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
- pipeline-modules/deployment-service/aws/istio-eks-module.yaml
- pipeline-modules/deployment-service/azure/basic-aks-module.yaml
- pipeline-modules/deployment-service/azure/istio-aks-module.yaml
- pipeline-modules/deployment-service/gcp/basic-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/istio-gke-regional.yaml
**Known issue  on k8s:**
If we made changes in existing code-pipes variable or added new variable & redeploy the application. The new variable deployed & updated on k8s cluster  as secrets & configmap, but Pod needs manual restart to use that secretes & configmap.
**Resolution :**  
Run the Helm upgrade command to apply the changes.
Use the helm upgrade command to update the deployment with the new Helm chart.
This will create a new Kubernetes deployment with the updated secrets and config maps.
Wait for the pods to restart.
Once the Helm upgrade command completes, Kubernetes will begin to restart the pods one-by-one with zero down type with below command : 
```
kubectl rollout restart deployment {{applicationName}}-deployment -n {{applicationName}}         
kubectl rollout status …
```
> VAN-2954 Rollout restart the pod on every deployment to get the updated change of Configmap & secrets

- Makefile
- scripts/container-load/README.md
- scripts/container-load/container-load.sh
- scripts/container-load/container-manifest.yaml
In order to avoid rate limiting issues with anonymous connections
to certain Docker registries, we will be hosting any images required
by our pipeline modules in ECR or GCR (maybe ACR in the future).
This introduces a shell script that pulls the relevant images, tags
them appropriately and pushes them up to ECR/GCR. The relevant images
are listed in a container-manifest.yaml file that is processed by
the script.
Also added a make target that logs into the various registries and
runs the script.
> VAN-3784 Automate process to push module containers

- pipeline-modules/app-service/aws/go-unittest.yaml
- pipeline-modules/app-service/aws/sonarcloud.yaml
- pipeline-modules/app-service/azure/go-build.yaml
- pipeline-modules/app-service/azure/go-unittest.yaml
- pipeline-modules/app-service/azure/make-target.yaml
- pipeline-modules/app-service/azure/sonarcloud.yaml
- pipeline-modules/app-service/gcp/go-unittest.yaml
- pipeline-modules/app-service/gcp/sonarcloud.yaml
- pipeline-modules/common/aws/git-clone.yaml
- pipeline-modules/common/azure/git-clone.yaml
Added sonarcloud.yaml and go-unittest.yaml for app integration
pipelines.
If the unittest modules is in the pipeline before the sonarcloud
module, then the test coverage information will be passed to
SonarCloud.
Also for GCP, switched the go-build module from using the cloud-
builders go image to the standard golang image. The support for
the cloud-builders image seems to be dropping as it is slow to
adopt new versions of golang.
As the sha_tag is now being passed in from the services, the places
where it was being exported as an env var have been removed.
> VAN-3734 Add SonarCloud and go-unittest modules

- pipeline-modules/app-service/gcp/go-build.yaml
- pipeline-modules/app-service/gcp/go-unittest.yaml
The CGO_ENABLED variable needs to be exported in the pipeline
script instead of in the env: section.
> VAN-3906 Fix CGO_ENABLED variable for GCP go modules

- pipeline-modules/app-service/gcp/sonarcloud.yaml
**Issue** :  When passing the sonar key as a Codepipes EVN variable ($$SONAR_KEY), the value is unable to parse this module.
**Fixed** : 
- Now in Sonar module we can pass the SONAR_TOKEN_KEY from  code pipes variables , input just define $$SONAR_TOKEN_KEY for GCP
- Added a new feature can Sonnar scan on Branch & PR  based on Webhook event type.
- Updated the PR to use the value in sonar PR analysis which declared as the environment in the pipeline:
"event_type"
"git_pr_key"
"git_pr_base"
"git_pr_head"
> VAN-3989 Update the Sonar scanner module for GCP

- pipeline-modules/common/aws/pipeline-config.yaml
- pipeline-modules/infra-service/aws/pipeline-config.yaml
Because of how go yaml v2 works, it needs all fields in lower case instead of camel case to be able to unmarshal it into the object.
The issue where vpc configuration was not working even after successfully setting it into the yaml, was cause because we had camel-case field names inside the config object. this change fixes it by changing it to lowercase.
> VAN-4071 fix aws vpc config

- assets/scripts/create-env-file.sh
fix create-env-file.sh script to not trim spaces from values
> VAN-4120 fix trimming spaces from env var values

- assets/scripts/create-env-file.sh
- assets/scripts/env.sh
- pipeline-modules/deployment-service/aws/app-runner.yaml
- pipeline-modules/deployment-service/gcp/cloud-run.yaml
This change introduces a new script `env.sh` and deprecates old environment variable handling system.
fixes issues where aws app-runner and gcp cloud-run templates were adding extra `""` on sensitive env variables while sending values to secret manager.
> VAN-4122 fix sensitive env var handling

- build-pipeline/int-prod-release.yml
- build-pipeline/prod-release.yml
- build-pipeline/staging-release.yml
The "ci-cd-module-release" template is now called "run-db-update".
> VAN-2358 Rename release template

- cloud-builders/helm/Dockerfile
- cloud-builders/helm/helm.bash
- pipeline-modules/deployment-service/gcp/basic-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/basic-helm.yaml
- pipeline-modules/deployment-service/gcp/istio-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/private-helm.yaml
In order to add "envsubst" as a tool that can be used to preprocess
Helm values.yaml it needs to be in the Helm container used in GCP.
To do this, we need to build the Helm container and push to cldcvr in
Docker Hub.
Changed the relevant deployment templates to use the new cpi-helm
container instead of having each module build it.
Added the preprocessing of values.yaml to replace environment
variables in the basic-helm and private-helm templates.
> VAN-4078 Add helm image to build locally

- pipeline-modules/common/aws/pipeline-config.yaml
* Updated the image to latest ECS Image "aws/codebuild/standard:7.0" so that cached image can be used which results in faster build.
* The image currently in use "aws/codebuild/standard:4.0" has been deprecated by AWS.
* Have tested the build, ECS Deploy with this already and those work without any issue.
> VAN-4153 Updated Image to latest for faster build and deploy

- pipeline-modules/common/gcp/pipeline-config.yaml
- pipeline-modules/deployment-service/gcp/basic-gke-regional.yaml
We've introduced a new input, **worker_pool**, to the GCP pipeline configuration. This allows us to specify the worker pool parameter. When we utilize a private worker pool, it should follow this syntax:
It's important to note that when the workerPool option is used, the machineType and diskSizeGb parameters will be automatically unset if no value is passed for the worker_pool parameter.
We unset machineType & diskSizeGb because it not required to pass with  workerPool.
{% if worker_pool %}
workerPool: {{ worker_pool }}
{% else %}. 
{% if pipeline_machine_type %}machineType: {{ pipeline_machine_type }}{% endif %}
{% if pipeline_disk_size_gb %}diskSizeGb: '{{ pipeline_disk_size_gb }}'{% endif %}
{% endif %}
**Note** : I have tested with feature & it working fine
If anyone want to set the …
> VAN-3785 Added the Cloud build Private Worker pool config in GCP 

- pipeline-modules/common/aws/pipeline-config.yaml
- pipeline-modules/common/gcp/pipeline-config.yaml
- pipeline-modules/infra-service/aws/pipeline-config.yaml
- pipeline-modules/infra-service/gcp/pipeline-config.yaml
This prevents the users from accidently setting an invalid value in the basic integer metrics.
> VN-4031 Set minimum values for pipeline configuration

- pipeline-modules/app-service/azure/bash.yaml
- pipeline-modules/app-service/azure/best-practice-appsec.yaml
- pipeline-modules/app-service/azure/docker-build-n-push.yaml
- pipeline-modules/app-service/azure/dotnet-build.yaml
- pipeline-modules/app-service/azure/fortify-selfhosted.yaml
- pipeline-modules/app-service/azure/fortify.yaml
- pipeline-modules/app-service/azure/go-build.yaml
- pipeline-modules/app-service/azure/go-scan.yaml
- pipeline-modules/app-service/azure/java-build.yaml
- pipeline-modules/app-service/azure/java-unit-test.yaml
- pipeline-modules/app-service/azure/publish-artifact.yaml
- pipeline-modules/app-service/azure/sonarcloud.yaml
- pipeline-modules/app-service/azure/sonarqube.yaml
- pipeline-modules/app-service/azure/sonatype-nexus.yaml
- pipeline-modules/deployment-service/azure/aks-cert-manager.yaml
- pipeline-modules/deployment-service/azure/avtok8s-kv-driver.yaml
- pipeline-modules/deployment-service/azure/azure-functions.yaml
- pipeline-modules/deployment-service/azure/azure-web-app.yaml
- pipeline-modules/deployment-service/azure/basic-aks-module.yaml
- pipeline-modules/deployment-service/azure/istio-aks-module.yaml
- pipeline-modules/deployment-service/azure/key-vault-driver.yaml
Since the pool_name is already set in the pipeline config module, there's no need to include it at every module level, so we will remove it.
> VAN-4298 Remove Pool_name from module level In Azure

- pipeline-modules/common/aws/pipeline-config.yaml
- pipeline-modules/infra-service/aws/pipeline-config.yaml
We are enhancing the "pipeline_compute_type" input to accept an enumeration (enum) where you can specify a list of available compute systems for running code builds on AWS.
> VAN-4366 Enhance the pipeline_compute_type input to accept an enum AWS pipelien conifg

- pipeline-modules/app-service/aws/semgrep.yaml
* Fixed Semgrep scan CI failing when there are more than 5 warnings.
* Fixed application name for Semgrep.
> VAN-4319 Fix Semgrep AWS CI Scan Failing

- pipeline-modules/common/aws/pipeline-config.yaml
- pipeline-modules/infra-service/aws/pipeline-config.yaml
As we know we have hard-coded the image docker image where the code build will run on the AWS Pipeline config. 
So we allow use to choose any image where you codebuild pipline will run .
We will enable users to select their CodeBuild image type from a list of Docker images offered by AWS. You can refer to the available options in the following documentation: [[AWS CodeBuild Build Environment Reference](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html)]
> VAN-4315 Add List of Runtime Docker image for Codebuild pipeline

- pipeline-modules/common/aws/pipeline-config.yaml
- pipeline-modules/infra-service/aws/pipeline-config.yaml
Updated timeoutInMinutes  & queuedTimeoutInMinutes min & max time  as suggested by[ aws doc](https://docs.aws.amazon.com/codebuild/latest/userguide/create-project-cli.html) in AWS infra pipeline config & Aws App pipeline config.
**timeoutInMinutes**
Optional. The number of minutes, is between 5 to 480 (8 hours), after which CodeBuild stops the build if it is not complete. If not specified, the default of 60 is used. To determine if and when CodeBuild stopped a build due to a timeout, run the batch-get-builds command. To determine if the build has stopped, look in the output for a buildStatus value of FAILED. To determine when the build timed out, look in the output for the endTime value associated with a phaseStatus value of TIMED_OUT.
**queuedTimeoutInMinutes**
Optional. The number of …
> VAN-4358 Update timeoutInMinutes  & queuedTimeoutInMinutes min & max time 

- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
- pipeline-modules/deployment-service/aws/istio-eks-module.yaml
- pipeline-modules/deployment-service/azure/basic-aks-module.yaml
- pipeline-modules/deployment-service/azure/istio-aks-module.yaml
- pipeline-modules/deployment-service/gcp/basic-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/istio-gke-regional.yaml
**Issue Discovery:**
In our CodePipes setup, I've observed that when we're deploying changes to our Stance application using Helm in a Kubernetes cluster, there's a safety mechanism in place. If a pod enters a crash loop for a continuous period of 300 seconds, it triggers an automatic rollback to the previous version.
```bash
helm upgrade --install -f values.yaml <release-name> . --atomic --timeout 300s
```
However, it's crucial to be aware that sometimes, even after a successful rollback, if the subsequent deployment attempt fails, the pipeline may still be marked as successful. This can be confusing for users as they may not immediately realize that Helm executed a rollback due to a failed deployment.
**Proposed Pull Request (PR):**
This PR aims to address the above-mentioned issues by …
> VAN-4322 Improve Status Reporting for Helm Rollback and Failed Deployments

- build-pipeline/staging-release.yml
Deployment to Azure staging is now controlled via variable "enableAzureStagingDeploy" which is defined in an AZDO variable group.
> VAN-4378 Add variable to control Azure deployment

- pipeline-modules/deployment-service/gcp/private-helm.yaml
This PR introduces a new feature in the CI/CD module for private Helm charts deployment, including the following enhancements:
- Users can now optionally override the Helm charts release name.
- Added a parameter input for enabling automatic Helm chart rollback in case of failure.
- Improved error reporting and rollback mechanisms for Helm charts in the event of deployment failure.
> VAN-4390 Enhance the private helm charts deployment ci-cd module.

- pipeline-modules/app-service/gcp/docker-compose-build.yaml
This commit adds error handling to the `docker-compose-build` Cloud Build module to ensure that the pipeline fails when the `docker compose build` command fails. The module now uses the `set -e` command to achieve this.
> VAN-4039 Add error handling for GCP Docker Compose

- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
AWS Infra Deployment is failing with the following error :  
`An unexpected error occurred: build has finished with status 'Failure': 'FAILED' (COMMAND_EXECUTION_ERROR) in 'BUILD': Error while executing command: echo 'kubectl get ingress -n "cldcvr-vanguard-demo-52dd07" -o=jsonpath="{.items[*].status.loadBalancer.ingress[*].hostname}" | tr -d \"' > cmd.sh
summary=$(retry.sh run "bash ./cmd.sh" 30 2)
. Reason: exit status 1`
> VAN-4417 Update basic-eks-regional.yaml as script was failing
