cldcvr/codepipes-ci-cd-modules

- pipeline-modules/deployment-service/gcp/basic-gke-regional.yaml
removed step ID from summary extraction step for basic gke template
> VAN-2102 removed step ID from summary extraction step

- pipeline-modules/deployment-service/aws/app-runner.yaml
- pipeline-modules/deployment-service/gcp/cloud-run.yaml
* Add support for public and private repositories
* Write jinja script to create the config files for source configuration and instance configuration for app ruunner
* Update the service  URL to HTTPS
* Pass env variables in the pipeline to the underlying app-runner
> VAN-1942 Fix application creds using pipeline env

- pipeline-modules/deployment-service/aws/pipeline-config.yaml
- pipeline-modules/deployment-service/gcp/pipeline-config.yaml
Store and get the variable names to be exported from an internal
environment variable __VG_EXPORTED_ENV_NAMES
> VAN-2165 Improve application variable exporting

- pipeline-modules/infra-service/aws/terraform.yaml
- pipeline-modules/infra-service/gcp/terraform.yaml
Now TF version is defined on the environment.
> VAN-2186 Make tf-version input internal

- pipeline-modules/deployment-service/aws/istio-app.yaml
- pipeline-modules/deployment-service/gcp/istio-app.yaml
Added pipeline modules for Istio for GCP and AWS
> VAN-2024 Added pipeline modules for Istio for GCP and AWS

- pipeline-modules/deployment-service/azure/pipeline-config.yaml
- pipeline-modules/deployment-service/azure/test_module.yaml
Added the pipeline_config and test_module pipeline modules to
the deployment-service for Azure.
This provides a minimal way to smoke test the flow from env to
deployment.
> VAN-2294 Add azure test_module for deployment

- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
The cluster, region and roleArn inputs are mandatory for this module
so they were added to the "required" list.
Also, fixed the defaults for several interal inputs that had "latest"
(I believe a cut/paste error)
> VAN-2312 Add required inputs to required section

- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
Removed required domain from Ingress.
> VAN-2347 Removed required domain from ingress

- helm/gcp/basic-gke/templates/deployment.yaml
- helm/gcp/basic-gke/templates/secret-env-values.yaml
- helm/gcp/basic-gke/values.yaml
- helm/gcp/istio-gke/sample_value.yaml
- helm/gcp/istio-gke/templates/deployment.yaml
- helm/gcp/istio-gke/templates/secret-env-values.yaml
- pipeline-modules/deployment-service/gcp/basic-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/cloud-run.yaml
- pipeline-modules/deployment-service/gcp/istio-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/pipeline-config.yaml
Use underlying secret managment objects to hide sensetive variables from users
* VAN-2288 Added client service account to cloud run 
* Added secret manager to cloud run template
* VAN-2219 Added k8s secret object for basic-gke helm chart
* VAN-2219 Added k8s secret object for istio-gke helm chart
* VAN-2075 Added jinja variable for application name
> VAN-2123 Update deployment templates to support secret values

- pipeline-modules/deployment-service/azure/pipeline-config.yaml
VAN-2382 Cleanup and organize environment variable in env file for azure pipeline.
Existing issues/improvments
https://cldcvr.atlassian.net/browse/VAN-2395
> VAN-2382 Cleanup and organise environment variable in env file for azure pipeline

- pipeline-modules/app-service/aws/bash.yaml
- pipeline-modules/app-service/aws/pipeline-summary.yaml
- pipeline-modules/app-service/azure/bash.yaml
- pipeline-modules/app-service/gcp/bash.yaml
- pipeline-modules/app-service/gcp/pipeline-summary.yaml
- pipeline-modules/deployment-service/aws/app-runner.yaml
- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
- pipeline-modules/deployment-service/aws/istio-app.yaml
- pipeline-modules/deployment-service/gcp/basic-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/cloud-run.yaml
- pipeline-modules/deployment-service/gcp/istio-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/test_module.yaml
Properties that cannot have default should be required.
> VAN-2399 Add explicit defaults to optional inputs

- pipeline-modules/app-service/aws/go-scan.yaml
- pipeline-modules/app-service/azure/go-scan.yaml
- pipeline-modules/app-service/gcp/go-scan.yaml
Add CI pipeline modules to scan vulnarable go code
using https://github.com/securego/gosec and
https://github.com/golangci/golangci-lint
> VAN-2340 App integration pipeline modules for code scanning

- pipeline-modules/app-service/aws/sonar-mvn.yaml
Added default value for sonar_config_file in sonar-mvn template
> VAN-2485 Added default value for sonar_config_file in sonar-mvn template

- pipeline-modules/app-service/azure/sonatype-nexus.yaml
This implementation works with service connections on azdo.
> VAN-2056 Add sonatype nexus IQ server template for azure

- pipeline-modules/deployment-service/aws/lambda-gateway.yaml
Uses serverless framework to deploy functions
Uses API gateway based lambda deployment template
Uses a container artifact based deployment template
> VAN-2543 Added lambda function app deployment template

- helm/gcp/istio-gke/templates/virtualservice.yaml
This reverts commit 04693504480dd5aa6cdb86797de481b496252599.
> Revert "VAN-2636 Fix syntax error in template if statement"

- helm/gcp/istio-gke/sample_value.yaml
- pipeline-modules/deployment-service/azure/aks-cert-manager.yaml
- pipeline-modules/deployment-service/azure/istio-app.yaml
- pipeline-modules/deployment-service/azure/pipeline-config.yaml
- pipeline-modules/infra-service/azure/terraform.yaml
- Added LB Type option for Istio Svc (Public or Private) in Azure
- Updated Helm Sample Value Chart used for testing
- Updated the path to helm chart for cert-manager in Azure
- Removed vmImage Pool
> VAN-1975 VM Pool Image changes and module updates

- pipeline-modules/infra-service/aws/component.yaml
- pipeline-modules/infra-service/aws/terraform.yaml
- pipeline-modules/infra-service/azure/component.yaml
- pipeline-modules/infra-service/azure/terraform.yaml
- pipeline-modules/infra-service/gcp/component.yaml
- pipeline-modules/infra-service/gcp/terraform.yaml
This module includes any additional infrastructure
components attached to the Environment.
> VAN-1128 Added component pipeline module

- pipeline-modules/deployment-service/gcp/cloud-run.yaml
- VAN-2640 Added custom domain support
- VAN-2640 Added custom domain support
> VAN 2640 add custom domain support

- helm/azure/istio-aks/sample_value copy.yaml
- helm/gcp/istio-gke/sample_value.yaml
Changed vanguard to vanguard-staging.
> VAN-3165 Remove use of old GCP project

- pipeline-modules/app-service/gcp/docker-compose-build-n-push.yaml
create the App module for CI , to build & push images using Docker compose for specific service
> VAN-3678 Added Build & push docker compose module

- pipeline-modules/app-service/aws/docker-build.yaml
- pipeline-modules/app-service/aws/docker-push.yaml
- pipeline-modules/app-service/aws/pack-containers.yaml
> VAN-3743 AWS buildpack implementation

- pipeline-modules/app-service/azure/node-app-build.yaml
- pipeline-modules/app-service/azure/node-build.yaml
- pipeline-modules/app-service/azure/publish-archive.yaml
- pipeline-modules/app-service/azure/publish-artifact.yaml
- pipeline-modules/app-service/azure/python-build.yaml
- pipeline-modules/deployment-service/azure/azure-functions.yaml
**Create below module :**
- Added the Build module for 
1. Nodejs 
2. Python 
- 
- Publish artifact on azure feed
- 
- deploy zip file to Azure function
> VAN-3831 Added build & deploy module for azure function

- pipeline-modules/app-service/aws/bash.yaml
- pipeline-modules/app-service/azure/bash.yaml
- pipeline-modules/app-service/azure/docker-build-n-push.yaml
- pipeline-modules/app-service/azure/go-build.yaml
- pipeline-modules/app-service/azure/java-unit-test.yaml
- pipeline-modules/app-service/azure/make-target.yaml
- pipeline-modules/app-service/gcp/bash.yaml
- pipeline-modules/app-service/gcp/docker-build-n-push.yaml
- pipeline-modules/app-service/gcp/docker-compose-build.yaml
- pipeline-modules/app-service/gcp/gke-skaffold.yaml
- pipeline-modules/app-service/gcp/go-build.yaml
- pipeline-modules/app-service/gcp/make-target.yaml
- pipeline-modules/app-service/gcp/node-build.yaml
Mark all uses of working_dir in pipeline modules internal.
> VAN-3824 Mark working_dir internal

- pipeline-modules/deployment-service/aws/ecs-template.yaml
Removed launch_type input from ECS Deployment
> VAN-3408 Removed launch_type input from ECS Deployment

- pipeline-modules/app-service/azure/publish-artifact.yaml
- pipeline-modules/deployment-service/azure/azure-functions.yaml
Fixing issue broken change after add feed_name in azure function module in ci-cd module
> VAN-3859 Fixing issue broken change after add feed_name in azure func

- helm/aws/basic-eks/templates/deployment.yaml
- helm/aws/basic-eks/templates/secret-env-values.yaml
- pipeline-modules/common/aws/pipeline-config.yaml
- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
**Issue** : When the variables are get masked on code pipes it unable to populate in k8s secretes for basic-eks-regional in aws.
**Resloved**: Make the changes in the deployment template of basic-eks-regional on aws
> VAN-3851 Need to fix the basic-eks-regional deployment template to inject secret Values 

- pipeline-modules/deployment-service/gcp/istio-app.yaml
Using this parameter we can increase & decrease the GKE ingress response timeout for istio Ingress gateway
> VAN-3896 Added timeout sec parameter for Istio Gke ingress

- pipeline-modules/deployment-service/azure/azure-functions.yaml
Added the Deployment method option In Azure function Module 
**deploymentMethod** - Deployment method
string. Required. Allowed values: 
auto (Auto-detect), 
zipDeploy (Zip Deploy), 
runFromPackage (Zip Deploy with Run From Package , make the wwwroot folder with read-only permission). 
Default value: auto.
Doc : https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v1?view=azure-pipelines#deployment-methods
> VAN-3730 Added the Deployment method option In Azure function Module

- pipeline-modules/deployment-service/aws/ecs-template.yaml
Appends the content of .secret.env to containerDef.json (Task Definition) to be deployed to ECS.
> VAN-4063 Added Secret Env variables to ECS Template from .secret.env

- pipeline-modules/deployment-service/aws/ecs-template.yaml
Changed ECS service_name to ecs_service_name as it was conflicting with service_name being passed by Codepipes.
> VAN-4127 Update ECS service_name to ecs_service_name

- pipeline-modules/common/aws/test_module.yaml
- pipeline-modules/deployment-service/aws/app-runner.yaml
- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
- pipeline-modules/deployment-service/aws/ecs-template.yaml
- pipeline-modules/deployment-service/aws/istio-eks-module.yaml
- pipeline-modules/deployment-service/aws/lambda-gateway-code.yaml
- pipeline-modules/deployment-service/aws/lambda-gateway-container.yaml
- pipeline-modules/deployment-service/aws/lambda-gateway.yaml
- pipeline-modules/deployment-service/azure/aks-cert-manager.yaml
- pipeline-modules/deployment-service/azure/avtok8s-kv-driver.yaml
- pipeline-modules/deployment-service/azure/azure-functions.yaml
- pipeline-modules/deployment-service/azure/azure-web-app.yaml
- pipeline-modules/deployment-service/azure/basic-aks-module.yaml
- pipeline-modules/deployment-service/azure/istio-aks-module.yaml
- pipeline-modules/deployment-service/azure/key-vault-driver.yaml
- pipeline-modules/deployment-service/azure/nginx-aks-module.yaml
- pipeline-modules/deployment-service/gcp/basic-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/basic-helm.yaml
- pipeline-modules/deployment-service/gcp/cloud-run.yaml
- pipeline-modules/deployment-service/gcp/istio-gke-regional.yaml
- pipeline-modules/deployment-service/gcp/private-helm.yaml
- backend change has logic in place which will ensure the backward compatibility and will ensure the handling of any special chars. 
- Further instead of just simple replacement the filter will use hash of the input in such cases.
- added sample filter usage to the test module
> VAN-4157 replacespecial filter to work without additional param

- pipeline-modules/deployment-service/gcp/cloud-run.yaml
References for cloudrun resource name nomenclature
https://stackoverflow.com/a/71073079
> VAN-4200 added custom filter to cloudrun module

- .editorconfig
- pipeline-modules/app-service/azure/publish-archive.yaml
> VAN-4209 make ArchiveFiles task silent

- pipeline-modules/infra-service/aws/pipeline-config.yaml
In PR is to update tag type & also make job_id as internal instead of optional
> VAN-4285 Updated  Infra Pipeline conifg for AWS

- pipeline-modules/deployment-service/gcp/cloud-run.yaml
* Added deploy time stamp so app.yaml is updated to deploy new app.yaml
* Updated config to add min and max instances and concurrency
* Added CloudCDN but there needs to be a manual LB creation
> VAN-4318 Updated the Cloud Run Module 

- pipeline-modules/common/aws/git-clone.yaml
Checks for terrarium.yaml in the given working directory. If present adds it outputs as base64
> TER-265 add terrarium.yaml data to outputs if present

- pipeline-modules/common/gcp/pipeline-config.yaml
ref: https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds#machinetype
> VAN-4388 add gcp machine type enum vals

- pipeline-modules/common/azure/git-clone.yaml
- pipeline-modules/common/gcp/git-clone.yaml
Check for terrarium.yaml in the given git directory for Azure and gcp. If present base64 encode it
> TER-389 check for terrarium.yaml for azure and gcp

- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
Error Handling for Ingress Absence: Implemented error handling to address scenarios where the ingress is not present. Previously, the absence of ingress would lead to pipeline failures. With this update, the system now captures and prints a detailed error message before exiting gracefully, ensuring smoother operations and easier debugging.
> VAN-4417 Error Handling for Ingress Absence for basic-eks-regional.yaml

- pipeline-modules/deployment-service/aws/basic-eks-regional.yaml
> VAN-4417 Fixed indentation
